# Generated by Django 5.2.7 on 2026-05-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_participant_dob_alter_participant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste an image URL here for the event card background', null=True),
        ),
    ]
