services:
  - type: web
    name: college-event-system
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
    startCommand: gunicorn college_event.wsgi:application